AWSTemplateFormatVersion: '2010-09-09'
Description: 'Aurora MySQL Blue/Green Deployment Test Environment'

Parameters:
  EnvironmentName:
    Type: String
    Default: aurora-bg-test
    Description: Environment name prefix

  # VPC Configuration
  UseExistingVpc:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Use existing VPC (true) or create new VPC (false)

  VpcId:
    Type: String
    Default: ''
    Description: Existing VPC ID (leave empty to use default VPC)

  VpcCidr:
    Type: String
    Default: '172.31.0.0/16'
    Description: VPC CIDR block for security group (default VPC uses 172.31.0.0/16)

  SubnetIds:
    Type: CommaDelimitedList
    Default: ''
    Description: Comma-separated subnet IDs (leave empty to auto-detect)

  # Cluster Configuration
  ClusterCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 3
    Description: Number of Aurora clusters (1-3)

  InstancesPerCluster:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 3
    Description: Instances per cluster (1-3)

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8

  DBName:
    Type: String
    Default: testdb

  EngineVersion:
    Type: String
    Default: '8.0.mysql_aurora.3.08.2'

  # Blue Cluster (Source) Instance Class
  # Supported instance types for Aurora MySQL: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.SupportAurora.html
  BlueInstanceClass:
    Type: String
    Default: db.r6g.large
    AllowedValues:
      # Burstable (T series) - for dev/test
      - db.t3.medium
      - db.t3.large
      - db.t4g.medium
      - db.t4g.large
      # Memory Optimized - R5 (Intel)
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
      - db.r5.24xlarge
      # Memory Optimized - R6g (Graviton2)
      - db.r6g.large
      - db.r6g.xlarge
      - db.r6g.2xlarge
      - db.r6g.4xlarge
      - db.r6g.8xlarge
      - db.r6g.12xlarge
      - db.r6g.16xlarge
      # Memory Optimized - R6i (Intel)
      - db.r6i.large
      - db.r6i.xlarge
      - db.r6i.2xlarge
      - db.r6i.4xlarge
      - db.r6i.8xlarge
      - db.r6i.12xlarge
      - db.r6i.16xlarge
      - db.r6i.24xlarge
      - db.r6i.32xlarge
      # Memory Optimized - R7g (Graviton3) - requires Aurora MySQL 3.03.1+
      - db.r7g.large
      - db.r7g.xlarge
      - db.r7g.2xlarge
      - db.r7g.4xlarge
      - db.r7g.8xlarge
      - db.r7g.12xlarge
      - db.r7g.16xlarge
      # Memory Optimized - R7i (Intel) - requires Aurora MySQL 3.08.0+
      - db.r7i.large
      - db.r7i.xlarge
      - db.r7i.2xlarge
      - db.r7i.4xlarge
      - db.r7i.8xlarge
      - db.r7i.12xlarge
      - db.r7i.16xlarge
      - db.r7i.24xlarge
      - db.r7i.48xlarge
      # Memory Optimized - R8g (Graviton4) - requires Aurora MySQL 3.08.0+
      - db.r8g.large
      - db.r8g.xlarge
      - db.r8g.2xlarge
      - db.r8g.4xlarge
      - db.r8g.8xlarge
      - db.r8g.12xlarge
      - db.r8g.16xlarge
      - db.r8g.24xlarge
      - db.r8g.48xlarge
      # Memory Optimized - X2g (Graviton2) - for large memory workloads
      - db.x2g.large
      - db.x2g.xlarge
      - db.x2g.2xlarge
      - db.x2g.4xlarge
      - db.x2g.8xlarge
      - db.x2g.12xlarge
      - db.x2g.16xlarge
    Description: Instance class for Blue (source) cluster - production workload

  # Green Cluster (Target) Instance Class  
  GreenInstanceClass:
    Type: String
    Default: db.r6g.xlarge
    AllowedValues:
      # Burstable (T series) - for dev/test
      - db.t3.medium
      - db.t3.large
      - db.t4g.medium
      - db.t4g.large
      # Memory Optimized - R5 (Intel)
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
      - db.r5.24xlarge
      # Memory Optimized - R6g (Graviton2)
      - db.r6g.large
      - db.r6g.xlarge
      - db.r6g.2xlarge
      - db.r6g.4xlarge
      - db.r6g.8xlarge
      - db.r6g.12xlarge
      - db.r6g.16xlarge
      # Memory Optimized - R6i (Intel)
      - db.r6i.large
      - db.r6i.xlarge
      - db.r6i.2xlarge
      - db.r6i.4xlarge
      - db.r6i.8xlarge
      - db.r6i.12xlarge
      - db.r6i.16xlarge
      - db.r6i.24xlarge
      - db.r6i.32xlarge
      # Memory Optimized - R7g (Graviton3) - requires Aurora MySQL 3.03.1+
      - db.r7g.large
      - db.r7g.xlarge
      - db.r7g.2xlarge
      - db.r7g.4xlarge
      - db.r7g.8xlarge
      - db.r7g.12xlarge
      - db.r7g.16xlarge
      # Memory Optimized - R7i (Intel) - requires Aurora MySQL 3.08.0+
      - db.r7i.large
      - db.r7i.xlarge
      - db.r7i.2xlarge
      - db.r7i.4xlarge
      - db.r7i.8xlarge
      - db.r7i.12xlarge
      - db.r7i.16xlarge
      - db.r7i.24xlarge
      - db.r7i.48xlarge
      # Memory Optimized - R8g (Graviton4) - requires Aurora MySQL 3.08.0+
      - db.r8g.large
      - db.r8g.xlarge
      - db.r8g.2xlarge
      - db.r8g.4xlarge
      - db.r8g.8xlarge
      - db.r8g.12xlarge
      - db.r8g.16xlarge
      - db.r8g.24xlarge
      - db.r8g.48xlarge
      # Memory Optimized - X2g (Graviton2) - for large memory workloads
      - db.x2g.large
      - db.x2g.xlarge
      - db.x2g.2xlarge
      - db.x2g.4xlarge
      - db.x2g.8xlarge
      - db.x2g.12xlarge
      - db.x2g.16xlarge
    Description: Instance class for Green (target) cluster - larger for faster binlog catchup

Conditions:
  CreateNewVpc: !Equals [!Ref UseExistingVpc, 'false']
  UseExistingVpcCondition: !Equals [!Ref UseExistingVpc, 'true']
  CreateCluster2: !Or [!Equals [!Ref ClusterCount, 2], !Equals [!Ref ClusterCount, 3]]
  CreateCluster3: !Equals [!Ref ClusterCount, 3]
  CreateInstance2: !Or [!Equals [!Ref InstancesPerCluster, 2], !Equals [!Ref InstancesPerCluster, 3]]
  CreateInstance3: !Equals [!Ref InstancesPerCluster, 3]
  # Combined conditions for Cluster2 instances
  CreateCluster2Instance2: !And
    - !Condition CreateCluster2
    - !Condition CreateInstance2
  CreateCluster2Instance3: !And
    - !Condition CreateCluster2
    - !Condition CreateInstance3
  # Combined conditions for Cluster3 instances
  CreateCluster3Instance2: !And
    - !Condition CreateCluster3
    - !Condition CreateInstance2
  CreateCluster3Instance3: !And
    - !Condition CreateCluster3
    - !Condition CreateInstance3

Resources:
  #============================================================================
  # New VPC Resources (only if CreateNewVpc)
  #============================================================================
  NewVPC:
    Type: AWS::EC2::VPC
    Condition: CreateNewVpc
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc

  NewSubnet1:
    Type: AWS::EC2::Subnet
    Condition: CreateNewVpc
    Properties:
      VpcId: !Ref NewVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-subnet-1

  NewSubnet2:
    Type: AWS::EC2::Subnet
    Condition: CreateNewVpc
    Properties:
      VpcId: !Ref NewVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-subnet-2

  #============================================================================
  # Security Group - VPC Internal Only (NO public access)
  #============================================================================
  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Aurora MySQL - VPC internal access only, NO public access
      VpcId: !If [CreateNewVpc, !Ref NewVPC, !Ref VpcId]
      # NO SecurityGroupIngress here - we add it via separate resource
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-aurora-sg

  # Allow access from VPC CIDR only
  AuroraSecurityGroupIngressVpc:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AuroraSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      CidrIp: !If [CreateNewVpc, '10.0.0.0/16', !Ref VpcCidr]
      Description: VPC internal access only

  # Allow self-reference (instances in same SG can communicate)
  AuroraSecurityGroupIngressSelf:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AuroraSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref AuroraSecurityGroup
      Description: Self-reference for cluster communication

  #============================================================================
  # DB Cluster Parameter Group (Required for Blue/Green Deployment)
  # Enables binlog for logical replication
  #============================================================================
  AuroraClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora MySQL parameter group with binlog enabled for Blue/Green
      Family: aurora-mysql8.0
      Parameters:
        binlog_format: ROW
        binlog_row_image: FULL
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cluster-pg

  #============================================================================
  # DB Subnet Group
  #============================================================================
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Aurora subnet group
      SubnetIds: !If 
        - CreateNewVpc
        - [!Ref NewSubnet1, !Ref NewSubnet2]
        - !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-subnet-group

  #============================================================================
  # Cluster 1
  #============================================================================
  Cluster1:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Sub ${EnvironmentName}-cluster-1
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterParameterGroupName: !Ref AuroraClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroup
      BackupRetentionPeriod: 1
      StorageEncrypted: true

  Cluster1Instance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-1-instance-1
      DBClusterIdentifier: !Ref Cluster1
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster1Instance2:
    Type: AWS::RDS::DBInstance
    Condition: CreateInstance2
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-1-instance-2
      DBClusterIdentifier: !Ref Cluster1
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster1Instance3:
    Type: AWS::RDS::DBInstance
    Condition: CreateInstance3
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-1-instance-3
      DBClusterIdentifier: !Ref Cluster1
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  #============================================================================
  # Cluster 2 (Conditional)
  #============================================================================
  Cluster2:
    Type: AWS::RDS::DBCluster
    Condition: CreateCluster2
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Sub ${EnvironmentName}-cluster-2
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterParameterGroupName: !Ref AuroraClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroup
      BackupRetentionPeriod: 1
      StorageEncrypted: true

  Cluster2Instance1:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster2
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-2-instance-1
      DBClusterIdentifier: !Ref Cluster2
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster2Instance2:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster2Instance2
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-2-instance-2
      DBClusterIdentifier: !Ref Cluster2
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster2Instance3:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster2Instance3
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-2-instance-3
      DBClusterIdentifier: !Ref Cluster2
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  #============================================================================
  # Cluster 3 (Conditional)
  #============================================================================
  Cluster3:
    Type: AWS::RDS::DBCluster
    Condition: CreateCluster3
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Sub ${EnvironmentName}-cluster-3
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterParameterGroupName: !Ref AuroraClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroup
      BackupRetentionPeriod: 1
      StorageEncrypted: true

  Cluster3Instance1:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster3
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-3-instance-1
      DBClusterIdentifier: !Ref Cluster3
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster3Instance2:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster3Instance2
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-3-instance-2
      DBClusterIdentifier: !Ref Cluster3
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

  Cluster3Instance3:
    Type: AWS::RDS::DBInstance
    Condition: CreateCluster3Instance3
    Properties:
      DBInstanceIdentifier: !Sub ${EnvironmentName}-cluster-3-instance-3
      DBClusterIdentifier: !Ref Cluster3
      DBInstanceClass: !Ref BlueInstanceClass
      Engine: aurora-mysql
      PubliclyAccessible: false

Outputs:
  BlueInstanceClass:
    Description: Blue (source) cluster instance class
    Value: !Ref BlueInstanceClass

  GreenInstanceClass:
    Description: Green (target) cluster instance class for Blue/Green deployment
    Value: !Ref GreenInstanceClass

  Cluster1Endpoint:
    Description: Cluster 1 Writer Endpoint
    Value: !GetAtt Cluster1.Endpoint.Address

  Cluster1ReaderEndpoint:
    Description: Cluster 1 Reader Endpoint
    Value: !GetAtt Cluster1.ReadEndpoint.Address

  Cluster2Endpoint:
    Condition: CreateCluster2
    Description: Cluster 2 Writer Endpoint
    Value: !GetAtt Cluster2.Endpoint.Address

  Cluster3Endpoint:
    Condition: CreateCluster3
    Description: Cluster 3 Writer Endpoint
    Value: !GetAtt Cluster3.Endpoint.Address

  SecurityGroupId:
    Description: Aurora Security Group ID
    Value: !Ref AuroraSecurityGroup

  CreateBlueGreenDeploymentCommand:
    Description: AWS CLI command to create Blue/Green deployment with specified Green instance class
    Value: !Sub |
      # Create Blue/Green deployment for Cluster 1 with Green instance class: ${GreenInstanceClass}
      aws rds create-blue-green-deployment \
        --blue-green-deployment-name ${EnvironmentName}-bg-deployment \
        --source arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${EnvironmentName}-cluster-1 \
        --target-db-instance-class ${GreenInstanceClass} \
        --region ${AWS::Region}

  EnvConfig:
    Description: Environment configuration
    Value: !Sub |
      export AURORA_CLUSTER_ENDPOINT="${Cluster1.Endpoint.Address}"
      export AURORA_DATABASE="${DBName}"
      export AURORA_USERNAME="${DBUsername}"
      export AURORA_PASSWORD="<your-password>"
      export BLUE_INSTANCE_CLASS="${BlueInstanceClass}"
      export GREEN_INSTANCE_CLASS="${GreenInstanceClass}"
